### ISSUE TITLE
用Chrome打开文章详情，会出现布局问题

### ISSUE THREAD

**Issue by junkor** [pizn/iLotus#3]
主题很赞，用Safari打开一切正常。用chrome的话【Version 41.0.2272.104 (64-bit)】，目前发现文章详情页会出现布局问题，可以用chrome访问 http://junkor.github.io/2015/03/27/Typed-Table-View-Controllers.html 进行查看。 不太懂前端，还请po主协助解决~

**Comment by junkor** [comment]
补充：是浏览器很宽的时候触发的，应该是界面宽度超过一个值的时候会触发重排成两列，变成两列的时候，有些文章会出现布局的错乱。

**Comment by pizn** [comment]
目前分栏功能不是很完美，不同标签兼容性有问题。要么直接将分栏功能去除，https://github.com/junkor/junkor.github.io/blob/master/static/style.css#L754，*-column-count: 改为 1; 或者文档编辑的时候，注意下格式和段落里面的关系。
