### ISSUE TITLE
css3的字体不显示

### ISSUE THREAD

**Issue by 007sair** [pizn/iLotus#4]
您好，将您的主题放在我的github上后发现css3的字体图标不显示了。
在本地使用jekyll serve时，http://127.0.0.1:4000/也不显示，改成http://localhost:4000/时图标就显示出来了，请问是什么原因？

**Comment by 007sair** [comment]
好像知道原因了，是config.yml里配置的url: http://localhost:4000的问题

**Comment by pizn** [comment]
:+1:
